<?php

namespace mpcmf\modules\authex\actions;

use mpcmf\modules\moduleBase\actions\action;
use mpcmf\modules\moduleBase\actions\actionsBase;
use mpcmf\modules\moduleBase\exceptions\actionException;
use mpcmf\system\acl\aclManager;
use mpcmf\system\pattern\singleton;

/**
 * Class tokenActions
 *
 * Tokens for access to api
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\actions;
 * @date 2015-08-17 15:33:33
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
class tokenActions
    extends actionsBase
{

    use singleton;

    /**
     * Set options inside this method
     *
     * @return mixed
     */
    public function setOptions()
    {
        // TODO: Implement setOptions() method.
    }

    /**
     * Bind some custom actions
     *
     * @return mixed
     * @throws actionException
     */
    public function bind()
    {
        $this->registerAction('api.token.generate', new action([
            'name' => 'Обновить токен',
            'method' => '_token_generate',
            'path' => '/token.generate',
            'http' => [
                'POST',
            ],
            'required' => [
            ],
            'template' => 'json.tpl',
            'useBase' => false,
            'relative' => false,
            'type' => action::TYPE__API_FREE_ACCESS,
            'acl' => [
                aclManager::ACL__GROUP_USER,
            ]
        ], $this));
        $this->registerAction('api.token.getInfo', new action([
            'name' => 'Информация о токене',
            'method' => '_token_getInfo',
            'path' => '/token.getInfo',
            'http' => [
                'GET',
                'POST',
            ],
            'required' => [
            ],
            'template' => 'json.pretty.tpl',
            'useBase' => false,
            'relative' => false,
            'type' => action::TYPE__API_FREE_ACCESS,
            'acl' => [
                aclManager::ACL__GROUP_GUEST,
                aclManager::ACL__GROUP_USER,
                aclManager::ACL__GROUP_ADMIN,
            ]
        ], $this));
    }
}