<?php
namespace mpcmf\modules\authex\entities;

use mpcmf\modules\moduleBase\entities\entityBase;
use mpcmf\system\pattern\singleton;

/**
 * Class invite
 *
 * Invite system
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\entities
 * @date 2015-10-01 12:35:13
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
class invite
    extends entityBase
{

    use singleton;
}