<?php

namespace mpcmf\modules\authex\entities;

use mpcmf\modules\moduleBase\entities\entityBase;
use mpcmf\system\pattern\singleton;

/**
 * Class userManagement
 *
 * User management system
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\entities
 * @date 2015-08-18 16:31:45
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
class userManagement
    extends entityBase
{

    use singleton;
}