<?php
namespace mpcmf\modules\authex\models;

use mpcmf\modules\moduleBase\models\modelBase;
use mpcmf\system\helper\communication\mail;
use mpcmf\system\pattern\singleton;
use mpcmf\system\view\smartyDriver;
use Slim\Slim;

/**
 * Class inviteModel
 *
 * Invite system
 *
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\models
 * @date 2015-10-01 12:35:13
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 *
 * @method string getMongoId() Mongo ID
 * @method $this setMongoId(string $value) Mongo ID
 * @method int getDate() Date
 * @method $this setDate(int $value) Date
 * @method string getEmail() Email
 * @method $this setEmail(string $value) Email
 * @method string getReferer() Referer
 * @method $this setReferer(string $value) Referer
 * @method string getInvite() Invite
 * @method $this setInvite(string $value) Invite
 * @method boolean getUsed() Used
 * @method $this setUsed(boolean $value) Used
 * @method getGroups
 * @method setGroups
 * @method setGroupIds(array $ids)
 * @method array getGroupIds()
 */
class inviteModel
    extends modelBase
{

    use singleton;

    public function generateInviteString($email)
    {
        return md5($email . microtime(true));
    }

    public function sendInvite(userModel $refererModel = null)
    {
        $email = $this->getEmail();
        $inviteString = $this->getInvite();
        $inviteLink = "http://filter01.sdstream.ru/invite/{$inviteString}";

        $smarty = $this->smarty();

        $smarty->appendData([
            'inviteLink' => $inviteLink,
            'refererModel' => $refererModel
        ]);

        $body = $smarty->render('inviteLetter.tpl', true);

        $mailer = mail::getInstance();
        $mailer->setFrom('no-reply@sdstream.ru');
        $mailer->addAddress($email);
        $mailer->Subject = 'SDS: Invite';
        $mailer->AltBody = '';
        $mailer->Body = $body;
        $mailer->isHTML();
        $mailer->send();
    }

    protected function smarty()
    {
        static $smarty;

        if ($smarty === null) {
            $smarty = new smartyDriver();
            $smarty->setTemplatesDirectory(__DIR__ . '/../templates/authex');
        }

        return $smarty;
    }
}