<?php

namespace mpcmf\modules\authex\models;

use mpcmf\modules\moduleBase\models\modelBase;
use mpcmf\system\pattern\singleton;

/**
 * Class userManagementModel
 *
 * User management system
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\models
 * @date 2015-08-18 16:31:45
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 *
 */
class userManagementModel
    extends modelBase
{

    use singleton;
}