<?php

namespace mpcmf\modules\authex\mappers;

use mpcmf\modules\moduleBase\mappers\mapperBase;
use mpcmf\system\pattern\singleton;

/**
 * Class userManagementMapper
 *
 * User management system
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\mappers
 * @date 2015-08-18 16:31:45
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
class userManagementMapper
    extends mapperBase
{

    use singleton;


    const FIELD__ID = '_id';

    public function getPublicName()
    {
        return 'User management';
    }

    /**
     * Entity map
     *
     * @return array[]
     */
    public function getMap()
    {
        return [
            self::FIELD__ID => [
                'getter' => 'getId',
                'setter' => 'setId',
                'role' => [
                    self::ROLE__PRIMARY_KEY => true,
                    self::ROLE__GENERATE_KEY => true,
                    self::ROLE__TITLE => true
                ],
                'type' => 'string',
                'formType' => 'text',
                'name' => 'MongoID',
                'description' => 'Уникальный идентификатор',
                'validator' => [
                    [
                        'type' => 'type.check',
                        'data' => [
                            'type' => 'string'
                        ]
                    ],
                    [
                        'type' => 'string.byRegex',
                        'data' => [
                            'pattern' => '/^[0-9a-f]{24}$/i'
                        ]
                    ]
                ],
                'options' => [
                    'required' => false,
                    'unique' => true
                ]
            ],
        ];
    }
}